version: '3'
services:
  product-service:
    build: ./services/product
    ports:
      - "8081:8081"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=ecommerce
    depends_on:
      - mongodb

  order-service:
    build: ./services/order
    ports:
      - "8082:8082"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=ecommerce
      - PRODUCT_SERVICE_URL=http://product-service:8081
    depends_on:
      - mongodb
      - product-service

  user-service:
    build: ./services/user
    ports:
      - "8083:8083"
    environment:
      - MONGO_URI=mongodb://mongodb:27017
      - DB_NAME=ecommerce
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    environment:
      - PRODUCT_SERVICE_URL=http://product-service:8081
      - ORDER_SERVICE_URL=http://order-service:8082
      - USER_SERVICE_URL=http://user-service:8083
    depends_on:
      - product-service
      - order-service
      - user-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
