server:
  port: 8080
  mode: development # development or production
  read_timeout: 10s
  write_timeout: 10s

db:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  dbname: backend_master
  sslmode: disable
  max_conns: 20
  timeout: 5s

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0

jwt:
  secret: your-secret-key
  access_token_ttl: 15m
  refresh_token_ttl: 24h

logger:
  level: debug # debug, info, warn, error
  file: logs/app.log

rate_limit:
  enabled: true
  requests: 100
  duration: 1m

cors:
  allowed_origins:
    - "*"
  allowed_methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed_headers:
    - Origin
    - Content-Type
    - Accept
    - Authorization
    - X-Request-ID
  max_age: 86400

swagger:
  enabled: true
